### ISSUE TITLE
request hep: Please update luarocks to the latest version of the mainline.

### ISSUE THREAD

**Issue by liuhengloveyou** [api7/lua-resty-redis-cluster#5]
thank you!

**Comment by membphis** [comment]
https://luarocks.org/modules/membphis/lua-resty-redis-cluster

release version v1.1 right now. I think you can fetch it from luarocks.org now. ^_^

related commit: https://github.com/iresty/lua-resty-redis-cluster/commit/087721be7ff1097aea48559bbdc569599887ece8
